### ISSUE TITLE
Sending notice without spaces adds extra quotes

### ISSUE THREAD

**Issue by tanelikaivola** [matjam/stationeersrcon#2]
Extra quotes are added for single word notices.

`srcon notice "test"` ends up as `"test"` in the game console (= incorrect)
`srcon notice "testing 123"` ends up as `testing 123` in the game console (=correct)

This is also logged on shell when sending commands:

```
$ srcon notice "test"
sent ""test"".
$ srcon notice "testing 123"
sent "testing 123".
```

**Comment by matjam** [comment]
This should be fixed now.

**Comment by matjam** [comment]
its case sensitive, I'm not sure I like that, but no time to sort it out right now. I tested my changes, let me know if there's any issues.
