### ISSUE TITLE
New command needed: hungerRate

### ISSUE THREAD

**Issue by tanelikaivola** [matjam/stationeersrcon#3]
New command was introduced to control hunger rate in the game and it's missing from the rcon tool.

This command should disable hunger completely: `srcon hungerRate 0`

**Comment by matjam** [comment]
woo, people are using the tool!

Added this command. Not tested. Also refactored a bunch of code to make it better.

**Comment by dtandersen** [comment]
When I set hunger to 0.5 is comes back as 0.

```
[root@ded stationeers]# srcon hungerRate 0.5
Hunger Rate is now 0
[root@ded stationeers]# srcon hungerRate .5
Hunger Rate is now 0
```

Linked to this tool in my docker image! https://hub.docker.com/r/dtandersen/stationeers/

edit: Moved to https://github.com/matjam/stationeersrcon/issues/5
